### ISSUE TITLE
Possible Mac support?

### ISSUE THREAD

**Issue by TMcSquared** [been-jamming/rubiks_cube#3]
Would love to see this working on Mac, hopefully that's in future plans!

**Comment by been-jamming** [comment]
Hi @TMcSquared! As far as I know, this should work on mac since mac is BSD based, but I don't have a mac to test it on. Have you tried compiling it using the steps for linux? If so, what else have you tried?

**Comment by been-jamming** [comment]
@TMcSquared did you get it working? I'm closing this soon if I don't hear back.

**Comment by been-jamming** [comment]
Haven't heard back, assuming it works on mac

**Comment by TMcSquared** [comment]
Oh I am so sorry, I wasn't really paying attention to my notifications (because I have a ton of them) I'll see what I can do to get this building on Mac when I have the time to.
